import Head from "next/head";
import Background from "./background";

const Error = () => {
  return (
    <>
      <Head>
        <title>wikiNow - Loading</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
        <div>Error</div>
      </Background>
    </>
  );
};

export default Error;
