import Head from "next/head";

const Loading = () => {
  return (
    <>
      <Head>
        <title>wikiNow - Loading</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gin_fizz-400">
        <div>Loading...</div>
      </main>
    </>
  );
};

export default Loading;
